name: MacBuild
on:
  workflow_dispatch:
  
  workflow_call:

jobs:
  build:
    name: macOS
    runs-on: macos-${{matrix.version}}
    strategy:
      matrix:
        version: [14, 15]
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install Libraries
        run: |
          haxelib setup ~/haxelib
          haxelib install hmm --quiet
          haxelib run hmm install --quiet

      - name: Extract current version
        id: get_version
        run: |
          CURRENT_VERSION=$(grep -oP 'build-number="\K[^"]*' project.xml)
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Compile
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          CURRENT_VERSION="${{ steps.get_version.outputs.current_version }}"
    
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            NEW_VERSION="${CURRENT_VERSION/-dev/-$COMMIT_SHA}"
            haxelib run lime build mac -Dcommit_sha=$COMMIT_SHA -Dbuild_number=$NEW_VERSION
          else
            haxelib run lime build mac -Dcommit_sha=$COMMIT_SHA -Dbuild_number=$CURRENT_VERSION
          fi

      - name: Make tar for relese
        run: |
          cd export/release/macos/bin
          tar czf macOS${{matrix.version}}.tar .

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: macOSBuild-${{matrix.version}}
          path: export/release/macos/bin/*.tar
          if-no-files-found: error
