name: WindowsBuild
on: 
  workflow_dispatch:
  
  workflow_call:

jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Determine cache strategy
        id: cache_strategy
        run: |
          if [[ "${{ github.event.workflow }}" == "Release" ]]; then
            echo "use_cache=true" >> $GITHUB_OUTPUT
          else
            echo "use_cache=false" >> $GITHUB_OUTPUT
          fi
          
      - name: cache Build
        id: cache
        if: steps.cache_strategy.outputs.use_cache == 'true'
        uses: actions/cache/restore@v4
        with:
          key: cache-build-haxelib
          restore-keys: |
            cache-build-haxelib
          path: |
            .haxelib/
          
      - name: Install Libraries
        if: steps.cache_strategy.outputs.use_cache == 'false'
        run: |
          haxelib setup C:\haxelib
          haxelib install hmm --quiet
          haxelib run hmm install --quiet

      - name: Extract current version
        id: get_version
        shell: pwsh
        run: |
          $content = Get-Content Project.xml -Raw
          if ($content -match 'build-number="([^"]*)"') {
              $CURRENT_VERSION = $matches[1]
              echo "current_version=$CURRENT_VERSION" >> $env:GITHUB_OUTPUT
              Write-Output "成功提取版本号: $CURRENT_VERSION"
          } else {
              Write-Error "在Project.xml中未找到build-number属性"
              exit 1
          }

      - name: Compile
        shell: pwsh
        run: |
          $COMMIT_SHA = (git rev-parse --short HEAD)
          $CURRENT_VERSION = "${{ steps.get_version.outputs.current_version }}"
          
          if ("${{ github.event_name }}" -eq "workflow_dispatch") {
            $NEW_VERSION = $CURRENT_VERSION -replace "-dev", "-$COMMIT_SHA"
            haxelib run lime build windows -Dcommit_sha=$COMMIT_SHA -Dbuild_number=$NEW_VERSION
          } else {
            haxelib run lime build windows -Dcommit_sha=$COMMIT_SHA -Dbuild_number=$CURRENT_VERSION
          }
          
      - name: Create Windows zip package
        shell: pwsh
        run: | 
          cd export\release\windows\bin
          Compress-Archive -Path * -DestinationPath windows.zip

      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild
          path: export\release\windows\bin\windows.zip
          if-no-files-found: error


      - name: Upload Artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild
          path: export\release\windows\bin\*.zip
          if-no-files-found: error
